### ISSUE TITLE
Issue with repo of issabel.org?

### ISSUE THREAD

**Issue by litebito** [furlongm/patchman#106]
Hi,

I see following issue with the repo's of issabel.org (an open source PBX solution)

Repository 60 : Base RPM Repository for Issabel x86_64
Downloading repo info (1/2):       100%|############################################################################################################################################|Time: 0:00:00
Found yum rpm repo - http://mirror.issabel.org/?release=4&arch=x86_64&repo=base/repodata/repomd.xml.xz
gunzip: Error -3 while decompressing data: incorrect header check
Traceback (most recent call last):
  File "/bin/patchman", line 593, in <module>
    main()
  File "/bin/patchman", line 588, in main
    showhelp = process_args(args)
  File "/bin/patchman", line 561, in process_args
    refresh_repos(args.repo, args.force)
  File "/bin/patchman", line 120, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python2.7/site-packages/patchman/repos/models.py", line 88, in refresh
    refresh_rpm_repo(self)
  File "/usr/lib/python2.7/site-packages/patchman/repos/utils.py", line 552, in refresh_rpm_repo
    refresh_yum_repo(mirror, data, mirror_url, ts)
  File "/usr/lib/python2.7/site-packages/patchman/repos/utils.py", line 417, in refresh_yum_repo
    primary_url, checksum, checksum_type = get_primary_url(mirror_url, data)
  File "/usr/lib/python2.7/site-packages/patchman/repos/utils.py", line 145, in get_primary_url
    context = etree.parse(BytesIO(extract(data, 'gz')), etree.XMLParser())
  File "lxml.etree.pyx", line 3197, in lxml.etree.parse (src/lxml/lxml.etree.c:64816)
  File "parser.pxi", line 1588, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:92901)
  File "parser.pxi", line 1617, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:93194)
  File "parser.pxi", line 1495, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:92003)
  File "parser.pxi", line 1011, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:88660)
  File "parser.pxi", line 577, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:84385)
  File "parser.pxi", line 676, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:85488)
  File "parser.pxi", line 627, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:84981)
lxml.etree.XMLSyntaxError: None

is this a bug in Patchman, or an issue with the repo ?

Thanks

**Comment by furlongm** [comment]
It looks like that URL is being identified as a mirrorlist, but it is not one.

What does the URL look like on the host?

**Comment by furlongm** [comment]
The mirrorlist looks broken:

http://mirror.issabel.org/?release=4&arch=x86_64&repo=base/repodata/repomd.xml.xz

gives these three:

http://repo.us.issabel.org/issabel/4/base/repodata/repomd.xml.xz/x86_64/ http://repo.issabel.org/issabel/4/base/repodata/repomd.xml.xz/x86_64/ http://repo.cl.issabel.org/issabel/4/base/repodata/repomd.xml.xz/x86_64/

so it looks like it is blindly creating a mirrorlist instead of giving a 404.

**Comment by furlongm** [comment]
Happy to keep this open as it's something we _should_ handle correctly. It is only that one misconfigured repo for now, so I didn't prioritize it yet, but I plan to get to it eventually. Also happy to take PRs to handle it.
