### ISSUE TITLE
Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by garbled1** [furlongm/patchman#137]
While working on a debian 10 repo:

Repository 5 : Debian 10.1 x86_64 repo at http://ftp.debian.org/debian/dists/buster/main/binary-amd64
Found deb repo - http://ftp.debian.org/debian/dists/buster/main/binary-amd64/Packages.xz
Downloading repo info:             100%|#################|Time: 0:00:13
Extracting packages:               100%|#################|Time: 0:00:25
Traceback (most recent call last):  54%|#########        |ETA:  8:05:46
  File "/usr/bin/patchman", line 596, in <module>
    main()
  File "/usr/bin/patchman", line 590, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 563, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/bin/patchman", line 121, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python2.7/dist-packages/repos/models.py", line 86, in refresh
    refresh_deb_repo(self)
  File "/usr/lib/python2.7/dist-packages/repos/utils.py", line 582, in refresh_deb_repo
    update_mirror_packages(mirror, packages)
  File "/usr/lib/python2.7/dist-packages/repos/utils.py", line 123, in update_mirror_packages
    packagetype=packagetype)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 509, in _create_object_from_params
    six.reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`patchman`.`packages_package`, CONSTRAINT `packages_package_name_id_2fbdcd85_fk_packages_packagename_id` FOREIGN KEY (`name_id`) REFERENCES `packages_packagename` (`id`))')

**Comment by furlongm** [comment]
Is this still an issue? I was trying to reproduce and am unable to.

**Comment by garbled1** [comment]
Yeah.. I can't get it to work at all with mysql and the debian 10 repo.  I was thinking maybe tonight I would wipe my db and restart with sqllite to see if the problem goes away...

**Comment by furlongm** [comment]
Using mysql on current buster:

```
# patchman -r
Refreshing metadata for all Repos

Repository 1 : Debian 10.2 x86_64 repo at http://repo.openbytes.ie/debian/dists/stretch/main/binary-amd64
Found deb repo - http://repo.openbytes.ie/debian/dists/stretch/main/binary-amd64/Packages.gz
Downloading repo info:             100%|###############################################################################################################################################################################|Time: 0:00:00
/usr/lib/python2.7/dist-packages/debian/deb822.py:693: UserWarning: Parsing of Deb822 data with python-apt's apt_pkg was requested but this cannot be done on non-file input.                                         |ETA:  --:--:--
  warnings.warn(msg)
Extracting packages:               100%|###############################################################################################################################################################################|Time: 0:00:00
Adding 4 new packages:             100%|###############################################################################################################################################################################|Time: 0:00:00

Repository 2 : Debian 10.2 x86_64 repo at http://security.debian.org/debian-security/dists/buster/updates/main/binary-amd64
Found deb repo - http://security-cdn.debian.org/debian-security/dists/buster/updates/main/binary-amd64/Packages.xz
Downloading repo info:             100%|###############################################################################################################################################################################|Time: 0:00:00
Extracting packages:               100%|###############################################################################################################################################################################|Time: 0:00:00
Adding 1175 new packages:          100%|###############################################################################################################################################################################|Time: 0:00:16

Repository 3 : Debian 10.2 x86_64 repo at http://deb.debian.org/debian/dists/buster/main/binary-amd64
Found deb repo - http://cdn-fastly.deb.debian.org/debian/dists/buster/main/binary-amd64/Packages.xz
Downloading repo info:             100%|###############################################################################################################################################################################|Time: 0:00:03
Extracting packages:               100%|###############################################################################################################################################################################|Time: 0:00:15
Adding 56894 new packages:         100%|###############################################################################################################################################################################|Time: 0:12:04
```

The sqlite version also works as expected. Perhaps it was a temporary glitch with your mirrors?

**Comment by garbled1** [comment]
OK, so..  the problem magically went away somehow. Maybe they had a glitch in the repo? I'm not sure.  I manually sync'd that repo this morning and it just worked.  Space aliens.
