### ISSUE TITLE
Issue when updating errata

### ISSUE THREAD

**Issue by ikheetleon** [furlongm/patchman#151]
I get an error when updating errata:

patchman -e
Downloading Errata Checksum:       100%|#################|Time: 0:00:00
Downloading CentOS Errata:         100%|#################|Time: 0:00:00
Processing 7794 Errata:            100%|#################|Time: 0:01:05
Traceback (most recent call last):  91%|###############  |ETA:  0:00:03
  File "/usr/bin/patchman", line 596, in <module>
    main()
  File "/usr/bin/patchman", line 590, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 580, in process_args
    update_errata(args.force)
  File "/usr/lib/python2.7/site-packages/packages/utils.py", line 92, in update_                                                                                                                                                             errata
    mark_security_updates()
  File "/usr/lib/python2.7/site-packages/packages/utils.py", line 293, in mark_s                                                                                                                                                             ecurity_updates
    affected_update.save()
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 808, in                                                                                                                                                              save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 838, in                                                                                                                                                              save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, upda                                                                                                                                                             te_fields)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 905, in                                                                                                                                                              _save_table
    forced_update)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 955, in                                                                                                                                                              _do_update
    return filtered._update(values) > 0
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 667, i                                                                                                                                                             n _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line                                                                                                                                                              1204, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line                                                                                                                                                              899, in execute_sql
    raise original_exception
django.db.utils.IntegrityError: (1062, "Duplicate entry '3364-166584-1' for key                                                                                                                                                              'packages_packageupdate_oldpackage_id_newpackage_f05335d2_uniq'")

Is there a way to clear the errate db and rebuild it?

**Comment by furlongm** [comment]
If you go into the Django Admin section, you should be able to select all errata and delete them.

**Comment by furlongm** [comment]
I can't reproduce so hopefully you were able to fix your issue. Feel free to reopen if not.
