### ISSUE TITLE
Web UI returns Server error 500 after a few weeks

### ISSUE THREAD

**Issue by litebito** [furlongm/patchman#167]
Hi,

I've been breaking my mind over this.
after some time (days or weeks), my patchman server just starts responding with an Error 500 when I goto http://hostname/patchman/login/?next=/patchman/dashboard/

I've looked for any clues in the logs in /var/log but cannot find anything there (nothing in the httpd logs either)

However, patchman-clients on other machines can still send reports without issues
The patchman cli also is still running without isses
I already tried : 
Cleaning out the browser cache : does not fix it
Restarting the vm : no fix
Tried different browsers : no fix
Tried browsing to the server from a different machine : no fix

Setup : 
- CentOS 7 on a VM
- Browsers : FF, Chrome, Opera on a Windows 10 pc

When I reinstall the machine from scratch, it works again, until after a few weeks

Is there any other log I can look into to try and analyze what is going on? I don't want to keep reinstalling the server

Thanks

**Comment by kiranos** [comment]
you can patch settings.py with

`LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/log/patchman_debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
`

To note you might have to touch and chmod the file 777 or similar first (just for testing perposes) Beacuse you will get an error if django cannot write to the file.

**Comment by litebito** [comment]
Thanks for the tip. Now I can see in the log what is wrong, I think it is an issue with the SITE_ID setting
(although nothing was changed to that over the last few weeks at least)

`Internal Server Error: /patchman/admin/login/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 393, in login
    return LoginView.as_view(**defaults)(request)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/views.py", line 124, in get_context_data
    current_site = get_current_site(self.request)
  File "/usr/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py", line 15, in get_current_site
    return Site.objects.get_current(request)
  File "/usr/lib/python2.7/site-packages/django/contrib/sites/models.py", line 63, in get_current
    return self._get_site_by_id(site_id)
  File "/usr/lib/python2.7/site-packages/django/contrib/sites/models.py", line 35, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Site matching query does not exist.`

**Comment by litebito** [comment]
Aha, 
I tried adding SITE_ID = x 
to /etc/patchman/local_settings.py
(I tried with 0, 1, 2)
it works again with SITE_ID = 2

Weeks ago when I installed the server, I did remove the "example.com" site via the admin gui and added a new one (I assume that will be site id 2 then)
Strange that it starts giving issues only since 2 days (I use the patchman dashboard a few days per week)? Any idea why it shows this behaviour?

Thanks

L.

**Comment by furlongm** [comment]
Was the webserver restarted in the last 2 or 3 days? That could cause it.

**Comment by litebito** [comment]
Yes,
the whole server was rebooted several times during the past few weeks

**Comment by furlongm** [comment]
I think the restarting caused the issue, after deleting SITE 1.  The correct thing to do is change the SITE_ID to a SITE_ID that exists before restarting the server.
