### ISSUE TITLE
patchman -a repositories Error

### ISSUE THREAD

**Issue by nuxster** [furlongm/patchman#171]
Hello!
When updating the repositories (patchman -a), I get the following error:

Repository 240 : Ubuntu 16.04 x86_64 repo at http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64
Found deb repo - http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/Packages.gz
Downloading repo info:             100%|############################################################################################################################################|Time: 0:00:00
/usr/local/lib/python2.7/dist-packages/debian/deb822.py:693: UserWarning: Parsing of Deb822 data with python-apt's apt_pkg was requested but this cannot be done on non-file input.|ETA:  --:--:--
  warnings.warn(msg)
.....
repos.models.MultipleObjectsReturned: get() returned more than one MirrorPackage -- it returned 2!

when working with Ubuntu 16.04.6 LTS.

repo:

deb http://archive.ubuntu.com/ubuntu xenial main restricted universe  multiverse
deb http://archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu xenial-security main restricted universe multiverse

What could be the problem?
Thanks!

P.S.

Debian GNU/Linux 10 (buster)
postgresql 11
Python 2.7.16

**Comment by furlongm** [comment]
Do you have the full stacktrace?

**Comment by nuxster** [comment]
Repository 240 : Ubuntu 16.04 x86_64 repo at http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64                                                  
Found deb repo - http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/Packages.gz                                                                  
Downloading repo info:             100%|############################################################################################################|Time: 0:00:00        
Extracting packages:               100%|############################################################################################################|Time: 0:00:01        
Obtaining stored packages:         100%|############################################################################################################|Time: 0:00:00        
Traceback (most recent call last):   6%|######                                                                                                      |ETA:  0:00:00        
  File "/usr/local/bin/patchman", line 4, in <module>
    __import__('pkg_resources').run_script('patchman==1.2.2', 'patchman')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script                                                                              
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1446, in run_script                                                                             
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/EGG-INFO/scripts/patchman", line 618, in <module>                                                 
    main()
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/EGG-INFO/scripts/patchman", line 612, in main                                                     
    showhelp = process_args(args)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/EGG-INFO/scripts/patchman", line 585, in process_args                                             
    refresh_repos(args.repo, args.force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/EGG-INFO/scripts/patchman", line 121, in refresh_repos                                            
    repo.refresh(force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/repos/models.py", line 86, in refresh                                                             
    refresh_deb_repo(self)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/repos/utils.py", line 582, in refresh_deb_repao                                                    
    update_mirror_packages(mirror, packages)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/repos/utils.py", line 96, in update_mirror_packages                                               
    MirrorPackage.objects.get(mirror=mirror, package=p).delete()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method                                                                   
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get                                                                               
    (self.model._meta.object_name, num)
repos.models.MultipleObjectsReturned: get() returned more than one MirrorPackage -- it returned 2!

**Comment by furlongm** [comment]
Out of interest, how was patchman installed?

**Comment by nuxster** [comment]
Installation was carried out from the source code according to your instructions.

**Comment by furlongm** [comment]
Can you print out what the package is in `/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/repos/utils.py` line 95?

**Comment by nuxster** [comment]
`ptext = 'Removing {0!s} obsolete packages:'.format(rlen)
 progress_info_s.send(sender=None, ptext=ptext, plen=rlen)
 for i, package in enumerate(removals):
     progress_update_s.send(sender=None, index=i + 1)
     package_id = PackageName.objects.get(name=package.name)
     epoch = package.epoch
     version = package.version
     release = package.release
     arch = PackageArchitecture.objects.get(name=package.arch)
     packagetype = package.packagetype
     p = Package.objects.get(name=package_id,
                             epoch=epoch,
                             version=version,
                             arch=arch,
                             release=release,
                             packagetype=packagetype)
     from repos.models import MirrorPackage
     with transaction.atomic():                (95 line)
     MirrorPackage.objects.get(mirror=mirror, package=p).delete()`

**Comment by furlongm** [comment]
I mean could you add `print(mirror, p)` to line 95.

**Comment by nuxster** [comment]
> I mean could you add `print(mirror, p)` to line 95.

Repository 240 : Ubuntu 16.04 x86_64 repo at http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64
Found deb repo - http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/Packages.gz
Downloading repo info:             100%|############################################################################################################################################|Time: 0:00:00
/usr/local/lib/python2.7/dist-packages/debian/deb822.py:693: UserWarning: Parsing of Deb822 data with python-apt's apt_pkg was requested but this cannot be done on non-file input.|ETA:  --:--:--
  warnings.warn(msg)
Extracting packages:               100%|############################################################################################################################################|Time: 0:00:01
Obtaining stored packages:         100%|############################################################################################################################################|Time: 0:00:00
(<Mirror: http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64>, <Package: systemd-container-229-4ubuntu21.23-amd64>)                                        |ETA:  0:00:00
Traceback (most recent call last):
  File "/usr/local/bin/patchman", line 4, in <module>
    import('pkg_resources').run_script('patchman==1.2.2', 'patchman')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/EGG-INFO/scripts/patchman", line 618, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/EGG-INFO/scripts/patchman", line 612, in main
    showhelp = process_args(args)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/EGG-INFO/scripts/patchman", line 585, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/EGG-INFO/scripts/patchman", line 121, in refresh_repos
    repo.refresh(force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/repos/models.py", line 86, in refresh
    refresh_deb_repo(self)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/repos/utils.py", line 583, in refresh_deb_repo
    update_mirror_packages(mirror, packages)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.2-py2.7.egg/repos/utils.py", line 97, in update_mirror_packages
    MirrorPackage.objects.get(mirror=mirror, package=p).delete()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
repos.models.MultipleObjectsReturned: get() returned more than one MirrorPackage -- it returned 2!

**Comment by furlongm** [comment]
Looks like somehow your database has two versions of `systemd-container-229-4ubuntu21.23-amd64`. I'm not sure how this happened, as it should be able to add two identical packages. You could navigate to the Packages section of the Django admin interface and delete the duplicate version of this package, and that should fix your issue.

**Comment by furlongm** [comment]
@nuxster Closing this issue for now, If deleting the duplicate package(s) does not fix the issues, please let me know and we can debug further.
