### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by metalcated** [furlongm/patchman#230]
Every fresh install I performed failed at this step at 47% using `patchman -a` 
Though, If I rerun the command again, it completes. 

```
Traceback (most recent call last):  47%|############################################################                                                                  |ETA:  0:13:13
  File "/usr/bin/patchman", line 674, in <module>
    main()
  File "/usr/bin/patchman", line 668, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 658, in process_args
    update_errata(args.force)
  File "/usr/lib/python2.7/dist-packages/packages/utils.py", line 91, in update_errata
    parse_errata(bunzip2(data), force)
  File "/usr/lib/python2.7/dist-packages/packages/utils.py", line 131, in parse_errata
    parse_errata_children(e, child.getchildren())
  File "/usr/lib/python2.7/dist-packages/packages/utils.py", line 178, in parse_errata_children
    name, epoch, ver, rel, dist, arch = pkg_re.match(pkg_str).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

```

**Comment by furlongm** [comment]
This was fixed in e235437ae7cab1a2db4a3eb0df979da661a3d6af.

I have a few more changes to make but I hope to cut a release soon with the fix.
