### ISSUE TITLE
django.db.utils.OperationalError when running patchman -p

### ISSUE THREAD

**Issue by FrankVanDamme** [furlongm/patchman#248]
When running patchman -p (or -a):

```Cleaning Reports for all Hosts

hostname.foo
Processing Reports for all Hosts
Reverse DNS matches
Traceback (most recent call last):   0%|                                                                                                                                                   |ETA:  --:--:--
  File "/usr/local/bin/patchman", line 4, in <module>
    __import__('pkg_resources').run_script('patchman==1.2.12', 'patchman')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.12-py2.7.egg/EGG-INFO/scripts/patchman", line 674, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.12-py2.7.egg/EGG-INFO/scripts/patchman", line 668, in main
    showhelp = process_args(args)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.12-py2.7.egg/EGG-INFO/scripts/patchman", line 635, in process_args
    process_reports(args.host, args.force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.12-py2.7.egg/EGG-INFO/scripts/patchman", line 473, in process_reports
    report.process(find_updates=False)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.12-py2.7.egg/reports/models.py", line 159, in process
    process_repos(report=self, host=host)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.12-py2.7.egg/reports/utils.py", line 45, in process_repos
    repo, priority = process_repo(repo_str, report.arch)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.12-py2.7.egg/reports/utils.py", line 237, in process_repo
    r_arch, c = machine_arches.get_or_create(name=arch)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/transaction.py", line 210, in __exit__
    connection.savepoint_rollback(sid)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/backends/base/base.py", line 348, in savepoint_rollback
    self._savepoint_rollback(sid)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/backends/base/base.py", line 308, in _savepoint_rollback
    cursor.execute(self.ops.savepoint_rollback_sql(sid))
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: (1305, 'SAVEPOINT s140152420624192_x1 does not exist')
```

There is just one host in my DB so far. The savepoint thing seems something about Django creating points to roll back transactions. I am running this in a docker container: https://hub.docker.com/r/gameflowtv/patchman/
it is based on Ubuntu 18.04 with Python 2.7.17 
The database runs on MariaDB 10.1.

pip list output:

```Package             Version
------------------- ---------------
asn1crypto          0.24.0
beautifulsoup4      4.6.0
certifi             2018.1.18
chardet             3.0.4
colorama            0.4.3
cracklib            2.9.2
cryptography        2.1.4
defusedxml          0.6.0
Django              1.11.29
django-bootstrap3   11.1.0
django-extensions   2.2.8
django-filter       1.1.0
django-guardian     1.4.9
django-tagging      0.4.6
djangorestframework 3.9.3
enum34              1.1.6
gunicorn            19.10.0
html5lib            0.999999999
humanize            1.0.0
idna                2.6
ipaddress           1.0.17
keyring             10.6.0
keyrings.alt        3.0
lxml                4.5.0
Markdown            2.6.9
mysqlclient         1.3.10
patchman            1.2.12
pip                 20.2.3
progressbar         2.5
pycrypto            2.6.1
Pygments            2.2.0
pygobject           3.26.1
pygooglechart       0.4.0
PyMySQL             0.8.0
pyOpenSSL           17.5.0
python-apt          1.6.5+ubuntu0.3
python-debian       0.1.36
python-magic        0.4.15
python-memcached    1.59
pytz                2018.3
pyxdg               0.25
PyYAML              3.12
requests            2.22.0
rpm                 4.14.1
SecretStorage       2.3.1
setuptools          39.0.1
six                 1.11.0
sqlparse            0.2.4
typing              3.7.4.3
urllib3             1.22
version-utils       0.3.0
webencodings        0.5
wheel               0.30.0
whitenoise          3.3.1```

**Comment by furlongm** [comment]
Is this still an issue or did it just occur once?

**Comment by furlongm** [comment]
Going to close this for now. Feel free to reopen if it reoccurs with the latest release.
