### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tosabyte** [furlongm/patchman#265]
Hi @furlongm 

My Patchman got an error when processing a report

```
Traceback (most recent call last):
  File "/usr/bin/patchman", line 674, in <module>
    main()
  File "/usr/bin/patchman", line 668, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 635, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 473, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python2.7/site-packages/reports/models.py", line 163, in process
    process_updates(report=self, host=host)
  File "/usr/lib/python2.7/site-packages/reports/utils.py", line 109, in process_updates
    sec_updates = parse_updates(report.sec_updates, True)
  File "/usr/lib/python2.7/site-packages/reports/utils.py", line 148, in parse_updates
    ulist[2])
IndexError: list index out of range
```

What could be the problem?
Thanks

**Comment by furlongm** [comment]
What version of the client is it? Can you try with the version from master branch?

**Comment by furlongm** [comment]
This should be fixed in the latest version
