### ISSUE TITLE
Error when downloading Errata

### ISSUE THREAD

**Issue by debben80** [furlongm/patchman#312]
Hello,

I've got the error below when downloading Errata.
This seems related to issue #270 

Any Idea?

`
Downloading Errata Checksum:       100%||Time: 0:00:00-
Downloading CentOS Errata:         100%||Time: 0:00:00-
Traceback (most recent call last):   0%||ETA:  --:--:--
  File "/usr/local/bin/patchman", line 4, in <module>
    __import__('pkg_resources').run_script('patchman==1.2.32', 'patchman')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.32-py2.7.egg/EGG-INFO/scripts/patchman", line 687, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.32-py2.7.egg/EGG-INFO/scripts/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.32-py2.7.egg/EGG-INFO/scripts/patchman", line 664, in process_args
    update_errata(args.force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.32-py2.7.egg/packages/utils.py", line 91, in update_errata
    parse_errata(bunzip2(data), force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.32-py2.7.egg/packages/utils.py", line 128, in parse_errata
    e = parse_errata_tag(child.tag, child.attrib, force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.32-py2.7.egg/packages/utils.py", line 152, in parse_errata_tag
    force=force)
  File "/usr/local/lib/python2.7/dist-packages/patchman-1.2.32-py2.7.egg/packages/utils.py", line 219, in create_erratum
    synopsis=synopsis)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python2.7/dist-packages/Django-1.11.29-py2.7.egg/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
packages.models.MultipleObjectsReturned: get() returned more than one Erratum -- it returned 2!
`

**Comment by furlongm** [comment]
Can you check if the instructions in https://github.com/furlongm/patchman/issues/294#issuecomment-796911858 help?

**Comment by debben80** [comment]
Hello,

I tried to delete all errata, problem persist.
Then I remove all packages and the problem was resolved.
But I remove by cleaning database cause there is a limit in Django Admin, and now I've some inconsistency in reports, so I'll start from scratch.

Thanks for your help.

**Comment by furlongm** [comment]
Going to close this for now. If it's still an issue with v2, feel free to reopen.
