### ISSUE TITLE
IndexError RHEL

### ISSUE THREAD

**Issue by ocnbb** [furlongm/patchman#315]
Hi,

I get the following "IndexError" on Red Hat Enterprise Linux 7 and 8 Server Reports: 

On RHEL 7 if "Sec updates:" and "Bug updates" both only contains:

```
Geladene Plugins: product-id, search-disabled-repos, subscription-manager
Geladene Plugins: product-id, search-disabled-repos, subscription-manager
```

patchman -p -d 
```
...
Traceback (most recent call last):
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 641, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 473, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python2.7/site-packages/reports/models.py", line 163, in process
    process_updates(report=self, host=host)
  File "/usr/lib/python2.7/site-packages/reports/utils.py", line 107, in process_updates
    bug_updates = parse_updates(report.bug_updates, False)
  File "/usr/lib/python2.7/site-packages/reports/utils.py", line 149, in parse_updates
    ulist[1],
IndexError: list index out of range
```

On RHEL 8 if "Sec updates:" contains:

```
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:06 am Di 13 Apr 2021 13:20:08 CEST.
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:05 am Di 13 Apr 2021 13:20:20 CEST.
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:07 am Di 13 Apr 2021 13:20:30 CEST.
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:04 am Di 13 Apr 2021 13:20:44 CEST.
Verfügbare Aktualisierungen
qemu-guest-agent.x86_64 15:4.2.0-34.module+el8.3.0+10437+1ca0c2ba.5 rhel-8-for-x86_64-appstream-rpms
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:07 am Di 13 Apr 2021 13:20:57 CEST.
Verfügbare Aktualisierungen
bpftool.x86_64             4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
kernel.x86_64              4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
kernel-core.x86_64         4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
kernel-devel.x86_64        4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
kernel-headers.x86_64      4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
kernel-modules.x86_64      4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
kernel-tools.x86_64        4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
kernel-tools-libs.x86_64   4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
python3-perf.x86_64        4.18.0-240.22.1.el8_3   rhel-8-for-x86_64-baseos-rpms
```

and "Bug updates:" contains:

```
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:08 am Di 13 Apr 2021 13:20:08 CEST.
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:08 am Di 13 Apr 2021 13:20:20 CEST.
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:09 am Di 13 Apr 2021 13:20:30 CEST.
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:08 am Di 13 Apr 2021 13:20:44 CEST.
Verfügbare Aktualisierungen
qemu-guest-agent.x86_64 15:4.2.0-34.module+el8.3.0+10437+1ca0c2ba.5 rhel-8-for-x86_64-appstream-rpms
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:10 am Di 13 Apr 2021 13:20:57 CEST.
Verfügbare Aktualisierungen
NetworkManager.x86_64          1:1.26.0-14.el8_3           rhel-8-for-x86_64-baseos-rpms
NetworkManager-libnm.x86_64    1:1.26.0-14.el8_3           rhel-8-for-x86_64-baseos-rpms
NetworkManager-team.x86_64     1:1.26.0-14.el8_3           rhel-8-for-x86_64-baseos-rpms
NetworkManager-tui.x86_64      1:1.26.0-14.el8_3           rhel-8-for-x86_64-baseos-rpms
bpftool.x86_64                 4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
crypto-policies.noarch         20210209-1.gitbfb6bed.el8_3 rhel-8-for-x86_64-baseos-rpms
crypto-policies-scripts.noarch 20210209-1.gitbfb6bed.el8_3 rhel-8-for-x86_64-baseos-rpms
file.x86_64                    5.33-16.el8_3.1             rhel-8-for-x86_64-baseos-rpms
file-libs.x86_64               5.33-16.el8_3.1             rhel-8-for-x86_64-baseos-rpms
kernel.x86_64                  4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
kernel-core.x86_64             4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
kernel-devel.x86_64            4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
kernel-headers.x86_64          4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
kernel-modules.x86_64          4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
kernel-tools.x86_64            4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
kernel-tools-libs.x86_64       4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
python3-magic.noarch           5.33-16.el8_3.1             rhel-8-for-x86_64-baseos-rpms
python3-perf.x86_64            4.18.0-240.22.1.el8_3       rhel-8-for-x86_64-baseos-rpms
selinux-policy.noarch          3.14.3-54.el8_3.3           rhel-8-for-x86_64-baseos-rpms
selinux-policy-targeted.noarch 3.14.3-54.el8_3.3           rhel-8-for-x86_64-baseos-rpms
sos.noarch                     3.9.1-7.el8_3               rhel-8-for-x86_64-baseos-rpms
systemd.x86_64                 239-41.el8_3.2              rhel-8-for-x86_64-baseos-rpms
systemd-libs.x86_64            239-41.el8_3.2              rhel-8-for-x86_64-baseos-rpms
systemd-pam.x86_64             239-41.el8_3.2              rhel-8-for-x86_64-baseos-rpms
systemd-udev.x86_64            239-41.el8_3.2              rhel-8-for-x86_64-baseos-rpms
zlib.x86_64                    1.2.11-16.2.el8_3           rhel-8-for-x86_64-baseos-rpms
zlib-devel.x86_64              1.2.11-16.2.el8_3           rhel-8-for-x86_64-baseos-rpms
```

patchman -p -d
```
...
Traceback (most recent call last):
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 641, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 473, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python2.7/site-packages/reports/models.py", line 163, in process
    process_updates(report=self, host=host)
  File "/usr/lib/python2.7/site-packages/reports/utils.py", line 107, in process_updates
    bug_updates = parse_updates(report.bug_updates, False)
  File "/usr/lib/python2.7/site-packages/reports/utils.py", line 150, in parse_updates
    ulist[2])
IndexError: list index out of range
```

If I delete the entries ("Letzte Prüfung auf..." and "Verfügbare Aktualisierungen") in both forms via Django Admin manually, it works.

Do you have any idea how to fix this permanently?

**Comment by furlongm** [comment]
Thanks for the report. What version of patchman-client is it?

I thought this was fixed in #272 by settings LC_ALL or LANGUAGE.

**Comment by ocnbb** [comment]
Thank you for your fast reply.

It is patchman-client-1.2.32-1

With CentOS 7 and 8 it works fine.

**Comment by furlongm** [comment]
Does setting either (or both) of the following work?

```
export LC_ALL=C
patchman-client
```

```
export LANGUAGE=en
patchman-client
```

**Comment by ocnbb** [comment]
Many thanks!

After some investigation I found out, that it works if I change `LC_ALL=C` to `export LC_ALL=C` in `/usr/sbin/patchman-client`.
