### ISSUE TITLE
MemoryError on patchman -r

### ISSUE THREAD

**Issue by RicardoJeronimo** [furlongm/patchman#349]
Hey,

After adding an openSUSE Leap 15 server to Patchman 1.2.33 and running `patchman -a`, I'm getting a MemoryError on "repo-oss x86_64":

```
Repository 172 : repo-oss x86_64
Checking http://download.opensuse.org/distribution/leap/15.3/repo/oss/repodata/repomd.xml.xz
Checking http://download.opensuse.org/distribution/leap/15.3/repo/oss/repodata/repomd.xml.bz2
Checking http://download.opensuse.org/distribution/leap/15.3/repo/oss/repodata/repomd.xml.gz
Checking http://download.opensuse.org/distribution/leap/15.3/repo/oss/repodata/repomd.xml
Downloading repo info (1/2):       100%|##############################################################################################|Time: 0:00:00
Found yum rpm repo - http://download.opensuse.org/distribution/leap/15.3/repo/oss/repodata/repomd.xml
Downloading repo info (2/2):       100%|##############################################################################################|Time: 0:00:00
Traceback (most recent call last):
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 647, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/bin/patchman", line 121, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python2.7/site-packages/repos/models.py", line 90, in refresh
    refresh_rpm_repo(self)
  File "/usr/lib/python2.7/site-packages/repos/utils.py", line 623, in refresh_rpm_repo
    refresh_yum_repo(mirror, data, mirror_url, ts)
  File "/usr/lib/python2.7/site-packages/repos/utils.py", line 488, in refresh_yum_repo
    packages = extract_yum_packages(data, primary_url)
  File "/usr/lib/python2.7/site-packages/repos/utils.py", line 284, in extract_yum_packages
    p_context = etree.iterparse(BytesIO(extracted),
MemoryError
```

Curiously enough, the previous repo (Repository 171 : repo-non-oss x86_64 - http://download.opensuse.org/distribution/leap/15.3/repo/non-oss/repodata/repomd.xml) is processed without any trouble.

Since this repo (172) isn't fully processed, I can't disable it on the web interface.

What could be the cause of this?

Thank you.

**Comment by RicardoJeronimo** [comment]
Solved after increasing memory to 16GB.
