### ISSUE TITLE
Refreshing repos results in get() returned more than one MirrorPackage

### ISSUE THREAD

**Issue by nalbyuites** [furlongm/patchman#35]
Please let me know if this is a patchman issue or something is wrong with the package list received from the repos. -

root@server$ PYTHONPATH=/srv/patchman /srv/patchman/sbin/patchman -r

Repository 15 : Debian 8.7 x86_64 repo at http://mirror.company.net/debian//dists/jessie/main/binary-amd64
Found deb repo - http://mirror.company.net/debian//dists/jessie/main/binary-amd64/Packages.xz
Downloading repo info:             100%|######################################################################################################################################################|Time: 0:00:00
Extracting packages:               100%|######################################################################################################################################################|Time: 0:00:24
Obtaining stored packages:         100%|######################################################################################################################################################|Time: 0:00:08
Traceback (most recent call last):   0%|                                                                                                                                                     |ETA:  --:--:--
  File "/srv/patchman/sbin/patchman", line 593, in <module>
    main()
  File "/srv/patchman/sbin/patchman", line 588, in main
    showhelp = process_args(args)
  File "/srv/patchman/sbin/patchman", line 561, in process_args
    refresh_repos(args.repo, args.force)
  File "/srv/patchman/sbin/patchman", line 120, in refresh_repos
    repo.refresh(force)
  File "/srv/patchman/patchman/repos/models.py", line 86, in refresh
    refresh_deb_repo(self)
  File "/srv/patchman/patchman/repos/utils.py", line 538, in refresh_deb_repo
    update_mirror_packages(mirror, packages)
  File "/srv/patchman/patchman/repos/utils.py", line 96, in update_mirror_packages
    MirrorPackage.objects.get(mirror=mirror, package=p).delete()
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
patchman.repos.models.MultipleObjectsReturned: get() returned more than one MirrorPackage -- it returned 2!

**Comment by furlongm** [comment]
This usually happens when mirrors are misconfigured. If you delete all repos and re-index them, does the same issue occur?

**Comment by furlongm** [comment]
Closing due to no response.
