### ISSUE TITLE
IntegrityError 1062 on mysql - Duplicate entry ' ' for key 'url' when processing reports.

### ISSUE THREAD

**Issue by nalbyuites** [furlongm/patchman#36]
$ PYTHONPATH=/srv/patchman /srv/patchman/sbin/patchman -p

Traceback (most recent call last):  69%|#############################              |ETA:  0:00:00
  File "/srv/patchman/sbin/patchman", line 593, in <module>
    main()
  File "/srv/patchman/sbin/patchman", line 588, in main
    showhelp = process_args(args)
  File "/srv/patchman/sbin/patchman", line 555, in process_args
    process_reports(args.host, args.force)
  File "/srv/patchman/sbin/patchman", line 430, in process_reports
    report.process(find_updates=False)
  File "/srv/patchman/patchman/reports/models.py", line 151, in process
    process_repos(report=self, host=host)
  File "/srv/patchman/patchman/reports/utils.py", line 45, in process_repos
    repo, priority = process_repo(repo_str, report.arch)
  File "/srv/patchman/patchman/reports/utils.py", line 266, in process_repo
    Mirror.objects.create(repo=repository, url=url)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 100, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
django.db.utils.IntegrityError: (1062, "Duplicate entry ' ' for key 'url'")

**Comment by furlongm** [comment]
Similar to #35 , I think this may be due to some repo/mirror misconfiguration. Looks like there shouldn't be two with the same URL and there is.

**Comment by furlongm** [comment]
Closing due to no response.

**Comment by mpevner** [comment]
Re-opening as I've run into the exact same issue. The client report that caused this issue reported the following repos:
```
'rpm' 'CentOS-7 - Base x86_64' 'base/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock' 'http://centos.mirror.constant.com/7.6.1810/os/x86_64' 
'rpm' 'Extra Packages for Enterprise Linux 7 - x86_64 x86_64' 'epel/x86_64' '99' 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64' 'http://mirror.nodesdirect.com/epel/7/x86_64' 
'rpm' 'CentOS-7 - Extras x86_64' 'extras/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock' 'http://mirror.fileplanet.com/centos/7.6.1810/extras/x86_64' 
'rpm' 'InfluxDB Repository - RHEL 7 x86_64' 'influxdb/7/x86_64' '99' 'https://repos.influxdata.com/rhel/7/x86_64/stable' 
'rpm' 'nginx repo x86_64' 'nginx/x86_64' '99' 'http://nginx.org/packages/centos/7/x86_64' 
'rpm' 'openbytes x86_64' 'openbytes' '99' 'http://repo.openbytes.ie/yum' 
'rpm' 'Remi' 'remi' '99's RPM repository for Enterprise Linux 7 - x86_64 x86_64' 'http://cdn.remirepo.net/enterprise/7/remi/mirror' 'http://repo1.dal.innoscale.net/remi/enterprise/7/remi/x86_64' 
'rpm' 'Remi' 'remi-php56' '99's PHP 5.6 RPM repository for Enterprise Linux 7 - x86_64 x86_64' 'http://cdn.remirepo.net/enterprise/7/php56/mirror' 'http://repo1.dal.innoscale.net/remi/enterprise/7/php56/x86_64' 
'rpm' 'Safe Remi' 'remi-safe' '99's RPM repository for Enterprise Linux 7 - x86_64 x86_64' 'http://cdn.remirepo.net/enterprise/7/safe/mirror' 'http://repo1.dal.innoscale.net/remi/enterprise/7/safe/x86_64' 
'rpm' 'CentOS-7 - Updates x86_64' 'updates/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock' 'http://mirror.wdc1.us.leaseweb.net/centos/7.6.1810/updates/x86_64' 
```
I'm hazarding a guess one of the remi repos is causing a trouble, but I don't see anything duplicate.
