### ISSUE TITLE
Version 2.0.1 crashes with UnicodeDecodeError when parsing repo deb.nodesource.com

### ISSUE THREAD

**Issue by macrotex** [furlongm/patchman#385]
Processing reports dies when  https://deb.nodesource.com:
```
Repository 70 : Debian 10.11 x86_64 repo at https://deb.nodesource.com/node_8.x/dists/buster/main/binary-amd64
Checking https://deb.nodesource.com/node_8.x/dists/buster/main/binary-amd64/Packages.xz
Checking https://deb.nodesource.com/node_8.x/dists/buster/main/binary-amd64/Packages.bz2
Checking https://deb.nodesource.com/node_8.x/dists/buster/main/binary-amd64/Packages.gz
Found deb repo - https://deb.nodesource.com/node_8.x/dists/buster/main/binary-amd64/Packages.gz
Downloading repo info:             100%|#####################################################################|Time: 0:00:00
Traceback (most recent call last):
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 647, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/bin/patchman", line 121, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python3/dist-packages/repos/models.py", line 84, in refresh
    refresh_deb_repo(self)
  File "/usr/lib/python3/dist-packages/repos/utils.py", line 652, in refresh_deb_repo
    packages = extract_deb_packages(data, mirror_url)
  File "/usr/lib/python3/dist-packages/repos/utils.py", line 321, in extract_deb_packages
    extracted = extract(data, url).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
Running version 2.0.1 of patchman:
```
# dpkg -l | grep patchman
ii  patchman-client               2.0.1-1                        all          Client for the patchman monitoring system.
ii  python3-patchman              2.0.1-1                        all          Django-based patch status monitoring tool for linux systems.
```

**Comment by macrotex** [comment]
It appears that the content from https://deb.nodesource.com/node_8.x/dists/buster/main/binary-amd64/Packages.gz is not extracted and thus when the method `.decode('utf-8')` is applied to uncompressed gzip data an error is, not surprisingly, thrown.

This leaves the question why the content is not being un-gzipped.

**Comment by furlongm** [comment]
Possibly the same issue as in https://github.com/furlongm/patchman/issues/368

**Comment by macrotex** [comment]
Yes, it very well might be. The content type sent in the response when downloading https://deb.nodesource.com/node_8.x/dists/buster/main/binary-amd64/Packages.gz is "text/html".

**Comment by furlongm** [comment]
Can you check if d89ec9a fixes the issue?
