### ISSUE TITLE
patchman-manage migrate get TypeError: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by vahidnameni** [furlongm/patchman#398]
I'm trying to install patchman with virtualenv + pip on Ubuntu 20.04 (clean install).
At first place I found `libmagic-dev` also needed to be installed beside of `gcc libxml2-dev libxslt1-dev virtualenv python3-dev zlib1g-dev`

When I run `patchman-manage` migrate i get this error:
```
Traceback (most recent call last):
  File "/home/patchman/patchman/bin/patchman-manage", line 39, in <module>
    execute_from_command_line(sys.argv)
  File "/home/patchman/patchman/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/patchman/patchman/lib/python3.8/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/patchman/patchman/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/patchman/patchman/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/patchman/patchman/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/patchman/patchman/lib/python3.8/site-packages/patchman/settings.py", line 139, in <module>
    conf_path = os.path.join(sitepackages, 'etc/patchman')
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list

```

**Comment by furlongm** [comment]
The virtualenv pip install is marked as not complete. IIRC there were a bunch of errors like this that needed to be resolved.

**Comment by stlinux** [comment]
bye
