### ISSUE TITLE
hosts.models.MultipleObjectsReturned: get() returned more than one Host

### ISSUE THREAD

**Issue by RicardoJeronimo** [furlongm/patchman#406]
Hey!

I noticed this error while using `patchman -lh -H srvdb` : 

```
Traceback (most recent call last):
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 612, in process_args
    list_hosts(args.host)
  File "/usr/bin/patchman", line 138, in list_hosts
    matching_hosts = get_hosts(hosts, 'Printing information')
  File "/usr/bin/patchman", line 76, in get_hosts
    host_obj = get_host(hosts, action)
  File "/usr/bin/patchman", line 59, in get_host
    host_obj = Host.objects.get(hostname__startswith=host)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
hosts.models.MultipleObjectsReturned: get() returned more than one Host -- it returned 2!
```

In this instance I was querying for a server named "srvdb", and I manage another named "srvdbdr". 
Another instance of this happening is with a cluster with 3 servers named "web01", "web02" and "web03".  When using `patchman -lh -H web0` the error above occurs.

It looks like the `-H` flag is using some sort of a wildcard when searching for the given host. 

I'm using patchman 1.2.33-1 and can't upgrade to version 2 since this is running on CentOS 7 in production. Is there any workaround for this?

Thanks!

**Comment by RicardoJeronimo** [comment]
Solved after upgrading to Patchman 2.0.3.
