### ISSUE TITLE
Process Reports: TypeError

### ISSUE THREAD

**Issue by kaiszy** [furlongm/patchman#424]
Hi,

when i process reports in crontab with

```usr/bin/patchman -r -A -p -c -d```

i get often the error:

```
Traceback (most recent call last):   8%|#               |ETA:  0:00:02
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 641, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 473, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python2.7/site-packages/reports/models.py", line 161, in process
    process_packages(report=self, host=host)
  File "/usr/lib/python2.7/site-packages/reports/utils.py", line 89, in process_packages
    error_message.send(sender=None, text=e)
  File "/usr/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/usr/lib/python2.7/site-packages/patchman/receivers.py", line 76, in print_error_message
    print(Style.BRIGHT + Fore.RED + text)
TypeError: cannot concatenate 'str' and 'OperationalError' objects
```

Then Patchman breaks and no reports are processed.

When i restart the above cmdline later by hand it works.

Some System Informations:

CentOS Linux release 7.9.2009 (Core)
Python 2.7.5

Best regards,
  Kai.

**Comment by furlongm** [comment]
Which version of patchman does this happen with?

**Comment by furlongm** [comment]
This is a no-longer-supported version of patchman, using Python 2.7 which is EOL. Please upgrade and let me know if the issue persists.
