### ISSUE TITLE
Control character in repo package list stops patchman update

### ISSUE THREAD

**Issue by rvn2p** [furlongm/patchman#478]
Hi,
my patchman (2.0.8-1 on debian)  instance stopped updating due to a weird character in a package update Description. I am aware that if the information provided by the veeam repo contains garbage that it will not extract its information (garbage in, garbage out principal), but i would like patchman to continue to run the other repos and update the computers in this situation but it stops the entire cronjob.

```
Repository 393 : Debian bookworm-sid x86_64 repo at http://repository.veeam.com/backup/linux/agent/dpkg/debian/public/dists/stable/veeam/binary-amd64
Found deb repo - http://repository.veeam.com/backup/linux/agent/dpkg/debian/public/dists/stable/veeam/binary-amd64/Packages.bz2
Downloading repo info:             100%|##########################################################################################################################################################################################################################|Time: 0:00:00
Traceback (most recent call last):
  File "/usr/bin/patchman", line 686, in <module>
    main()
  File "/usr/bin/patchman", line 680, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 646, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/bin/patchman", line 121, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python3/dist-packages/repos/models.py", line 84, in refresh
    refresh_deb_repo(self)
  File "/usr/lib/python3/dist-packages/repos/utils.py", line 638, in refresh_deb_repo
    packages = extract_deb_packages(data, mirror_url)
  File "/usr/lib/python3/dist-packages/repos/utils.py", line 314, in extract_deb_packages
    extracted = extract(data, url).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 30503: invalid start byte

```

Possible bad charater in Package list:
![grafik](https://user-images.githubusercontent.com/20243819/220620713-25a77fa2-a856-430b-87d6-728d1f650eb3.png)

**Comment by rvn2p** [comment]
Reportet at veeam (pending moderator approval) https://forums.veeam.com/veeam-agents-for-linux-mac-aix-solaris-f41/invalid-character-in-repository-package-description-t85231.html
