### ISSUE TITLE
Process pending Reports fails with IndexError: pop index out of range

### ISSUE THREAD

**Issue by enekux** [furlongm/patchman#485]
Hi,

we have recently noticed that next error is being thrown when running `/usr/bin/patchman -a`:

```
Reverse DNS check disabled
Traceback (most recent call last):  87%|###############################################################################################################################                   |ETA:  0:00:00
  File "/usr/bin/patchman", line 686, in <module>
    main()
  File "/usr/bin/patchman", line 680, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 640, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 472, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python3/dist-packages/reports/models.py", line 155, in process
    process_repos(report=self, host=host)
  File "/usr/lib/python3/dist-packages/reports/utils.py", line 44, in process_repos
    repo, priority = process_repo(repo_str, report.arch)
  File "/usr/lib/python3/dist-packages/reports/utils.py", line 213, in process_repo
    r_id = repo.pop(2)
IndexError: pop index out of range
```

After checking more in detail we have seen that the error is thrown specifically when running `/usr/bin/patchman -p` (flag to "Process pending Reports").

Are you noticing the same error maybe? Or is something local?

Thank you and regards,

**Comment by enekux** [comment]
Ok seems to be fixed now after I deleted all old reports via Django portal, thanks

**Comment by enekux** [comment]
I am re-opening the issue since it has happened again when processing the reports

**Comment by furlongm** [comment]
Do you have a sample of the report that it fails on?

**Comment by enekux** [comment]
Hi,

when I run `/usr/bin/patchman -p` I get the next error below (currently there are like 133 reports):

```
Processing Reports for all Hosts
Reverse DNS check disabled
Traceback (most recent call last):  87%|#################################################        |ETA:  0:00:00
  File "/usr/bin/patchman", line 686, in <module>
    main()
  File "/usr/bin/patchman", line 680, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 640, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 472, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python3/dist-packages/reports/models.py", line 155, in process
    process_repos(report=self, host=host)
  File "/usr/lib/python3/dist-packages/reports/utils.py", line 44, in process_repos
    repo, priority = process_repo(repo_str, report.arch)
  File "/usr/lib/python3/dist-packages/reports/utils.py", line 213, in process_repo
    r_id = repo.pop(2)
IndexError: pop index out of range
```

**Comment by furlongm** [comment]
Do you have a sample of the report that it fails on?

You should be able to see the next report to be processed in the UI.

Alternatively add

`print(repo)`

to `/usr/lib/python3/dist-packages/reports/utils.py` line 212

**Comment by enekux** [comment]
```
/usr/bin/patchman -p
Processing Reports for all Hosts
Reverse DNS check disabled
['rpm', 'Docker CE Stable - x86_64 x86_64', 'docker-ce-stable', '99', 'https://download.docker.com/linux/fedora/37/x86_64/stable']
['rpm', 'Fedora 37 - x86_64 x86_64', 'fedora', '99', 'http://mirror.23m.com/fedora/linux/releases/37/Everything/x86_64/os']
['rpm', 'Fedora 37 openh264 (From Cisco) - x86_64 x86_64', 'fedora-cisco-openh264', '99', 'https://codecs.fedoraproject.org/openh264/37/x86_64/os']
['rpm', 'Fedora Modular 37 - x86_64 x86_64', 'fedora-modular', '99', 'http://ftp.uni-bayreuth.de/linux/fedora/linux/releases/37/Modular/x86_64/os']
['rpm', 'openbytes x86_64', 'openbytes', '99', 'https://repo.openbytes.ie/patchman/el8']         |ETA:  0:00:00
['rpm', 'Fedora 37 - x86_64 - Updates x86_64', 'updates', '99', 'http://mirror.dogado.de/fedora/linux/updates/37/Everything/x86_64']
['rpm', 'Fedora Modular 37 - x86_64 - Updates x86_64', 'updates-modular', '99', 'http://mirror.dogado.de/fedora/linux/updates/37/Modular/x86_64']
['rpm']unner-lnx-02-ci.va repos     87%|#################################################        |ETA:  0:00:00
Traceback (most recent call last):
  File "/usr/bin/patchman", line 686, in <module>
    main()
  File "/usr/bin/patchman", line 680, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 640, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 472, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python3/dist-packages/reports/models.py", line 155, in process
    process_repos(report=self, host=host)
  File "/usr/lib/python3/dist-packages/reports/utils.py", line 44, in process_repos
    repo, priority = process_repo(repo_str, report.arch)
  File "/usr/lib/python3/dist-packages/reports/utils.py", line 214, in process_repo
    r_id = repo.pop(2)
IndexError: pop index out of range
```

**Comment by furlongm** [comment]
Looks like your reports have a line like so:

`['rpm']`

Can you confirm that in the UI?

If so, can you give the output of `dnf repolist` from one of the affected hosts?

**Comment by enekux** [comment]
When I commented on #78 I updated the repo files and remove the `\`.

As you can see in the image above, the repo does not contain the `\` anymore but we still get the error...

**Comment by furlongm** [comment]
Hmm, ok.

The problematic report was definitely made on the same host, and after the repo was fixed?

And the report shown in the UI is definitely the same report that is having the error, right? Maybe print the report id to confirm that too?

**Comment by enekux** [comment]
Hi @furlongm,
Actually the problem has been fixed after the repo was fixed (removed the `\`) and old reports were removed.
So the problem is gone, thank you and congratulations for this great app ;)
