### ISSUE TITLE
Celery:  IntegrityError(1062, "Duplicate entry 'https://packages.gitlab.com/runner/gitlab-runner/ubuntu/dists...' for key 'url'")

### ISSUE THREAD

**Issue by tabacha** [furlongm/patchman#531]
python3-patchman 2.0.14-1 On ubuntu:

Celery gives the follwing stacktrace in Logfile:
```
Nov 22 12:15:28 patchman celery[15221]: [2023-11-22 13:15:28,906: INFO/MainProcess] Task reports.tasks.process_report[dd103f9d-408d-4f8c-9bb5-93a0a4a1df7a] received
Nov 22 12:15:29 patchman celery[15232]: [2023-11-22 13:15:29,058: ERROR/ForkPoolWorker-3] Task reports.tasks.process_report[926da8cc-d56d-4600-b059-59691f237464] raised unexpected: IntegrityError(1062, "Duplicate entry 'https://packages.gitlab.com/runner/gitlab-runner/ubuntu/dists..
.' for key 'url'")
Nov 22 12:15:29 patchman celery[15232]: Traceback (most recent call last):
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
Nov 22 12:15:29 patchman celery[15232]:     return self.cursor.execute(sql, params)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
Nov 22 12:15:29 patchman celery[15232]:     return self.cursor.execute(query, args)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
Nov 22 12:15:29 patchman celery[15232]:     res = self._query(query)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 316, in _query
Nov 22 12:15:29 patchman celery[15232]:     self._do_get_result(db)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 147, in _do_get_result
Nov 22 12:15:29 patchman celery[15232]:     self._result = result = self._get_result()
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 349, in _get_result
Nov 22 12:15:29 patchman celery[15232]:     return self._get_db().store_result()
Nov 22 12:15:29 patchman celery[15232]: MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'https://packages.gitlab.com/runner/gitlab-runner/ubuntu/dists...' for key 'url'")
Nov 22 12:15:29 patchman celery[15232]: The above exception was the direct cause of the following exception:
Nov 22 12:15:29 patchman celery[15232]: Traceback (most recent call last):
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 451, in trace_task
Nov 22 12:15:29 patchman celery[15232]:     R = retval = fun(*args, **kwargs)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 734, in __protected_call__
Nov 22 12:15:29 patchman celery[15232]:     return self.run(*args, **kwargs)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/reports/tasks.py", line 29, in process_report
Nov 22 12:15:29 patchman celery[15232]:     report.process(verbose=True)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/reports/models.py", line 155, in process
Nov 22 12:15:29 patchman celery[15232]:     process_repos(report=self, host=host)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/reports/utils.py", line 44, in process_repos
Nov 22 12:15:29 patchman celery[15232]:     repo, priority = process_repo(repo_str, report.arch)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/reports/utils.py", line 259, in process_repo
Nov 22 12:15:29 patchman celery[15232]:     Mirror.objects.create(repo=repository, url=url)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 85, in manager_method
Nov 22 12:15:29 patchman celery[15232]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 453, in create
Nov 22 12:15:29 patchman celery[15232]:     obj.save(force_insert=True, using=self.db)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 739, in save
Nov 22 12:15:29 patchman celery[15232]:     self.save_base(using=using, force_insert=force_insert,
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 776, in save_base
Nov 22 12:15:29 patchman celery[15232]:     updated = self._save_table(
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 881, in _save_table
Nov 22 12:15:29 patchman celery[15232]:     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 919, in _do_insert
Nov 22 12:15:29 patchman celery[15232]:     return manager._insert(
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 85, in manager_method
Nov 22 12:15:29 patchman celery[15232]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 1270, in _insert
Nov 22 12:15:29 patchman celery[15232]:     return query.get_compiler(using=using).execute_sql(returning_fields)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
Nov 22 12:15:29 patchman celery[15232]:     cursor.execute(sql, params)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 66, in execute
Nov 22 12:15:29 patchman celery[15232]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
Nov 22 12:15:29 patchman celery[15232]:     return executor(sql, params, many, context)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 79, in _execute
Nov 22 12:15:29 patchman celery[15232]:     with self.db.wrap_database_errors:
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/utils.py", line 90, in __exit__
Nov 22 12:15:29 patchman celery[15232]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
Nov 22 12:15:29 patchman celery[15232]:     return self.cursor.execute(sql, params)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
Nov 22 12:15:29 patchman celery[15232]:     return self.cursor.execute(query, args)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
Nov 22 12:15:29 patchman celery[15232]:     res = self._query(query)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 316, in _query
Nov 22 12:15:29 patchman celery[15232]:     self._do_get_result(db)
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 147, in _do_get_result
Nov 22 12:15:29 patchman celery[15232]:     self._result = result = self._get_result()
Nov 22 12:15:29 patchman celery[15232]:   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 349, in _get_result
Nov 22 12:15:29 patchman celery[15232]:     return self._get_db().store_result()
Nov 22 12:15:29 patchman celery[15232]: django.db.utils.IntegrityError: (1062, "Duplicate entry 'https://packages.gitlab.com/runner/gitlab-runner/ubuntu/dists...' for key 'url'")
Nov 22 12:15:29 patchman celery[15221]: [2023-11-22 13:15:29,953: INFO/MainProcess] Task reports.tasks.process_report[df77af6a-e5b3-42f3-911c-b7158f91c7d3] received
```

**Comment by furlongm** [comment]
Does this error still occur with patchman 3?

**Comment by furlongm** [comment]
If this error still occurs on patchman 3, please reopen the issue.
