### ISSUE TITLE
Missing mysql fields/table since 3.0.4

### ISSUE THREAD

**Issue by julienleboeuf** [furlongm/patchman#538]
Since upgrading to 3.0.4, patchman is broken.

Various commands crash with a mysql error :
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "La table 'patchman_db.hosts_host_modules' n'existe pas")

The above exception was the direct cause of the following exception:
```
or
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Champ 'reports_report.modules' inconnu dans field list")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/patchman", line 705, in <module>
    main()
  File "/usr/bin/patchman", line 699, in main
    showhelp = process_args(args)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/bin/patchman", line 656, in process_args
    clean_reports(args.host)
  File "/usr/bin/patchman", line 240, in clean_reports
    host.clean_reports(timestamp)
  File "/usr/lib/python3/dist-packages/hosts/models.py", line 122, in clean_reports
    remove_reports(self, timestamp)
  File "/usr/lib/python3/dist-packages/hosts/utils.py", line 50, in remove_reports
    for report in reports:
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Champ 'reports_report.modules' inconnu dans field list")
```

Browsing a host detail results in : 500 - Server Error
Reports page too

During upgrade of python3-patchman, there was some database modification :
```
0 static files copied to '/var/lib/patchman/static', 166 unmodified.
No changes detected
Operations to perform:
  Synchronize unmigrated apps: admindocs, arch, bootstrap3, celery, django_extensions, django_filters, domains, hosts, humanize, messages, modules, operatingsystems, packages, reports, repos, rest_framework, staticfiles, util
  Apply all migrations: admin, auth, contenttypes, sessions, sites, tagging
Synchronizing apps without migrations:
  Creating tables...
    Creating table modules_module
    Running deferred SQL...
Running migrations:
  No migrations to apply.
```

Installed on a debian 12 server with mariadb 11.14 (

**Comment by furlongm** [comment]
I'm not sure an upgrade is supported. But you could try `patchman-manage makemigrations` and then `patchman-manage migrate --run-syncdb`

**Comment by julienleboeuf** [comment]
Already tried, not better

**Comment by julienleboeuf** [comment]
Can you provide table info so we can manually create it ?

**Comment by julienleboeuf** [comment]
A bad surprise is that patchman-client upgrade is mandatory otherwise we get an error 500

**Comment by furlongm** [comment]
The older client should still work - do you have a stacktrace from the server?

**Comment by enekux** [comment]
+1

**Comment by jaydeepch15** [comment]
+1
