### ISSUE TITLE
Patchman-client throwing error

### ISSUE THREAD

**Issue by jaydeepch15** [furlongm/patchman#544]
After sorting this out https://github.com/furlongm/patchman/issues/538
Now when Tried to push data from client server i.e 

```
[root@server01 ~]# /usr/sbin/patchman-client -r
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>500 - Server Error</title>
</head>
<body>
<h1>500 - Server Error</h1>
<p>There has been an error. It has been reported to the site administrators and should be fixed shortly.<p>
</body>
</html>
```

I also tried upgrade patchman-client but same error.

On patchman server when hit `patchman -a`

get below

```
Processing Reports for all Hosts
Error: OS, kernel or arch not sent with report 14123
Error: OS, kernel or arch not sent with report 14124
Error: OS, kernel or arch not sent with report 14125
Error: OS, kernel or arch not sent with report 14128
Error: OS, kernel or arch not sent with report 14126
Error: OS, kernel or arch not sent with report 14127
```

then it proceed further even shows old and new packages per client server, But still not on Dashboard

**Comment by furlongm** [comment]
Can you enable DEBUG on the server and post the stacktrace from the apache log?

**Comment by Pavel077** [comment]
Hello.

I had 500 error too, [this solution](https://github.com/furlongm/patchman/issues/351) helped me.

**Comment by jaydeepch15** [comment]
@furlongm @Pavel077 
I tried above mentioned workaround but it did not fix my issue. Below is apache configuration for patchman
```
root@awslpatchman:~# cat /etc/apache2/conf-enabled/patchman.conf
Define patchman_pythonpath /usr/lib/python3/dist-packages
WSGIScriptAlias /patchman ${patchman_pythonpath}/patchman/wsgi.py
WSGIPythonPath ${patchman_pythonpath}
WSGIApplicationGroup %{GLOBAL}

<Directory ${patchman_pythonpath}>
    <Files wsgi.py>
        Require all granted
    </Files>
    AllowOverride All
</Directory>

Alias /patchman/static "/var/lib/patchman/static"
<Location /patchman/static>
    SetHandler None
</Location>

<Directory /var/lib/patchman/static>
    Require all granted
</Directory>

<Location /patchman/reports/upload>
    # Add the IP addresses of your client networks/hosts here
    # to allow uploading of reports
    #Require ip 127.0.0.0/255.0.0.0
    Require all granted
    #Require ip ::1/128
</Location>
```

I below are the apache error logs
```
[Tue Jan 02 04:41:44.965684 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646] Internal Server Error: /patchman/reports/upload/
[Tue Jan 02 04:41:44.965824 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646] Traceback (most recent call last):
[Tue Jan 02 04:41:44.965856 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]   File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
[Tue Jan 02 04:41:44.965892 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]     response = get_response(request)
[Tue Jan 02 04:41:44.965918 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
[Tue Jan 02 04:41:44.965947 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 02 04:41:44.965976 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]   File "/usr/lib/python3/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Tue Jan 02 04:41:44.966041 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]     return view_func(*args, **kwargs)
[Tue Jan 02 04:41:44.966059 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]   File "/usr/lib/python3/dist-packages/reports/views.py", line 43, in upload
[Tue Jan 02 04:41:44.966066 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]     report.parse(data, meta)
[Tue Jan 02 04:41:44.966071 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]   File "/usr/lib/python3/dist-packages/reports/models.py", line 89, in parse
[Tue Jan 02 04:41:44.966078 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646]     setattr(self, attr, data.get(attr).strip())
[Tue Jan 02 04:41:44.966084 2024] [wsgi:error] [pid 626:tid 140449146709568] [client 172.51.113.250:42646] AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by furlongm** [comment]
Are you running the latest version of  `patchman-client` on the client?

**Comment by jaydeepch15** [comment]
@furlongm Yes, It is latest.
```patchman-client |  | 3.0.4 | 1 | all | deb |```

**Comment by furlongm** [comment]
And the server is latest too?

**Comment by furlongm** [comment]
Can you try with 3.0.7 on both server and client?

**Comment by mastro-pi** [comment]
this version solves the problem (which I also had). Thx.. and keep up your good work

**Comment by jaydeepch15** [comment]
on patchman server I tried `apt upgrade patchman*`
below is snippet of output
````

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. I
t is strongly recommended you activate it. See: https://docs.djangoproject.com/en/3.2/ref/databases/#mysql-sql-mode
Operations to perform:
  Synchronize unmigrated apps: admindocs, bootstrap3, celery, django_extensions, django_filters, humanize, messages, rest_framework, staticfiles, util
  Apply all migrations: admin, arch, auth, contenttypes, domains, hosts, modules, operatingsystems, packages, reports, repos, sessions, sites, tagging
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying arch.0001_initial... FAKED
  Applying domains.0001_initial... FAKED
  Applying operatingsystems.0001_initial... FAKED
  Applying packages.0001_initial... FAKED
  Applying repos.0001_initial... FAKED
  Applying modules.0001_initial... FAKED
  Applying operatingsystems.0002_initial... FAKED
  Applying hosts.0001_initial... FAKED
  Applying hosts.0002_initial... FAKED
  Applying hosts.0003_host_modules...Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1050, "Table 'hosts_host_modules' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/patchman-manage", line 39, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python3/dist-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python3/dist-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/schema.py", line 98, in add_field
    super().add_field(model, field)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 488, in add_field
    return self.create_model(field.remote_field.through)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 345, in create_model
    self.execute(sql, params or None)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'hosts_host_modules' already exists")
dpkg: error processing package python3-patchman (--configure):
 installed python3-patchman package post-installation script subprocess returned error exit status 1
Setting up patchman-client (3.0.7-1) .
```

```
root@awslpatchman:~#   dpkg -l patchman
dpkg-query: no packages found matching patchman


root@awslpatchman:~#   dpkg -l patchman-client
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version      Architecture Description
+++-===============-============-============-==========================================
ii  patchman-client 3.0.7-1      all          Client for the patchman monitoring system.
```
Is there any way to check patchman server version?

**Comment by furlongm** [comment]
You may need to remove the table added here:

https://github.com/furlongm/patchman/issues/538#issuecomment-1845622931

**Comment by jaydeepch15** [comment]
I dropped table using `DROP TABLE hosts_host_modules;`

now getting below error, no idea how to fix it.

```
WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, b
y escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/3.
2/ref/databases/#mysql-sql-mode
Operations to perform:
  Synchronize unmigrated apps: admindocs, bootstrap3, celery, django_extensions, django_filters, humanize, messages, res
t_framework, staticfiles, util
  Apply all migrations: admin, arch, auth, contenttypes, domains, hosts, modules, operatingsystems, packages, reports, r
epos, sessions, sites, tagging
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying hosts.0003_host_modules... OK
  Applying reports.0001_initial... FAKED
  Applying reports.0002_report_modules...Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1060, "Duplicate column name 'modules'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/patchman-manage", line 39, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python3/dist-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python3/dist-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/schema.py", line 98, in add_field
    super().add_field(model, field)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 522, in add_field
    self.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1060, "Duplicate column name 'modules'")
dpkg: error processing package python3-patchman (--configure):
 installed python3-patchman package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 python3-patchman
Sending report to patchman server ...
The following data has been submitted for processing:
```

**Comment by furlongm** [comment]
Could you clean the existing reports and try with newer client on Amazon Linux 2?

**Comment by jaydeepch15** [comment]
I followed below steps
1. Removed patchman-client from Amazon-2 Instance (Assuming it will delete all associated reports with it)
2. Re-install it again. (this version we get from yum repository patchman-client.noarch 0:2.0.18-1)
```
[root@client01 ~]# cat /etc/yum.repos.d/openbytes.repo
[openbytes]
name=openbytes
baseurl=https://repo.openbytes.ie/patchman/el8
enabled=1
gpgcheck=0
```


3. Ran ` patchman-client -r` and Below is output
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>500 - Server Error</title>
</head>
<body>
<h1>500 - Server Error</h1>
<p>There has been an error. It has been reported to the site administrators and should be fixed shortly.<p>
</body>
</html>
```

4. Then Edited openbytes.repo
```
[root@client01 ~]# cat /etc/yum.repos.d/openbytes.repo
[openbytes]
name=openbytes
baseurl=https://repo.openbytes.ie/patchman/el9
enabled=1
gpgcheck=0
```

5. Got below error while installing 
```
[root@client01 ~]$ sudo yum install patchman-client
Loaded plugins: priorities, update-motd, upgrade-helper
Repository packages-microsoft-com-prod is listed more than once in the configuration
245 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package patchman-client.noarch 0:3.0.7-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================
 Package                                    Arch                              Version                            Repository                            Size
============================================================================================================================================================
Installing:
 patchman-client                            noarch                            3.0.7-1                            openbytes                             13 k

Transaction Summary
============================================================================================================================================================
Install  1 Package

Total size: 13 k
Installed size: 22 k
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
ERROR You need to update rpm to handle:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by patchman-client-3.0.7-1.noarch
RPM needs to be updated
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2024-01-17.03-28.DOByt7.yumtx
```

**Comment by cracksmokinmonkeys** [comment]
I'm seeing the same issues on reports/upload.

No matter how I install: Docker, rpm, or python virtual environment.

I am able to get past hurdles for the type of installation to the point when I can run the application using gunicorn, apache, or nginx and trying to upload give the results you see above.

My gunicorn output shows:

Internal Server Error: /reports/upload/
Traceback (most recent call last):
  File "/opt/patchman/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/patchman/lib64/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/patchman/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/patchman/lib64/python3.9/site-packages/reports/views.py", line 43, in upload
    report.parse(data, meta)
  File "/opt/patchman/lib64/python3.9/site-packages/reports/models.py", line 89, in parse
    setattr(self, attr, data.get(attr).strip())
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by furlongm** [comment]
Can you try the following patch?

```
diff --git a/reports/models.py b/reports/models.py
index 7fdc7fb..75cad75 100644
--- a/reports/models.py
+++ b/reports/models.py
@@ -86,7 +86,8 @@ class Report(models.Model):
                  'reboot']

         for attr in attrs:
-            setattr(self, attr, data.get(attr).strip())
+            if data.get(attr):
+                setattr(self, attr, data.get(attr))

         if self.host is not None:
```

**Comment by cracksmokinmonkeys** [comment]
I'm not familiar with diff patches.  I changed the code specified in the diff and I still receive errrors:

Not Found: /patchman/static/css/base.css
Not Found: /patchman/static/js/button-post.js
Not Found: /patchman/static/js/ajax-jquery.js
Not Found: /patchman/static/js/button-post.js
Not Found: /patchman/static/img/icon-no.gif
Not Found: /patchman/static/css/base.css
Not Found: /patchman/static/js/ajax-jquery.js
Not Found: /patchman/static/js/button-post.js
Not Found: /reports/upload/
Internal Server Error: /reports/upload/
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/reports/views.py", line 43, in upload
    report.parse(data, meta)
  File "/usr/lib/python3.9/site-packages/reports/models.py", line 90, in parse
    setattr(self, attr, data.get(attr))
AttributeError: 'Report' object has no attribute 'attr'

**Comment by jaydeepch15** [comment]
@furlongm 
I am still getting below error
```
[root@client01 ~]$ sudo yum install patchman-client
Loaded plugins: priorities, update-motd, upgrade-helper
Repository packages-microsoft-com-prod is listed more than once in the configuration
245 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package patchman-client.noarch 0:3.0.7-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================
 Package                                    Arch                              Version                            Repository                            Size
============================================================================================================================================================
Installing:
 patchman-client                            noarch                            3.0.7-1                            openbytes                             13 k

Transaction Summary
============================================================================================================================================================
Install  1 Package

Total size: 13 k
Installed size: 22 k
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
ERROR You need to update rpm to handle:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by patchman-client-3.0.7-1.noarch
RPM needs to be updated
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2024-01-17.03-28.DOByt7.yumtx
 ```
 
 can you please let me know how to apply above patch, I am not much familiar with python.

**Comment by Shakall1944** [comment]
Hello,

I have the same issue on the lastest patchman server and client:

Installed Middleware:
[&#x27;django.middleware.security.SecurityMiddleware&#x27;,
 &#x27;django.middleware.cache.UpdateCacheMiddleware&#x27;,
 &#x27;django.middleware.http.ConditionalGetMiddleware&#x27;,
 &#x27;django.contrib.sessions.middleware.SessionMiddleware&#x27;,
 &#x27;django.middleware.common.CommonMiddleware&#x27;,
 &#x27;django.middleware.csrf.CsrfViewMiddleware&#x27;,
 &#x27;django.contrib.auth.middleware.AuthenticationMiddleware&#x27;,
 &#x27;django.contrib.messages.middleware.MessageMiddleware&#x27;,
 &#x27;django.middleware.clickjacking.XFrameOptionsMiddleware&#x27;,
 &#x27;django.middleware.cache.FetchFromCacheMiddleware&#x27;]



Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/reports/views.py", line 43, in upload
    report.parse(data, meta)
  File "/usr/lib/python3/dist-packages/reports/models.py", line 89, in parse
    if data.get(attr):

Exception Type: AttributeError at /reports/upload/
Exception Value: &#x27;NoneType&#x27; object has no attribute &#x27;strip&#x27;
</textarea>
  <br><br>
  <input type="submit" value="Share this traceback on a public website">
  </div>
</form>
</div>


I've even tried patch mentioned above but as you can see it's this the same error.

Do you have news regarding this topic?

Thank you

**Comment by furlongm** [comment]
@jaydeepch15 it looks like you applied the patch but it's still failing on `strip` which should no longer exist. Does restarting the web server help to reload the file?

**Comment by furlongm** [comment]
Can you try commit 0404e57c8fc61ce33a88c3ccd7b672a08cdf1083  in PR #594 ? Hoping this will fix this issue too
