### ISSUE TITLE
Module matching query does not exist. Rocky 9 Linux

### ISSUE THREAD

**Issue by Ezio1001** [furlongm/patchman#557]
Hello, I've been receiving this error when running patchman -r, it appears as if it's stopping with Repo 1 only, I tried a workaround by using the command "patchman --repo 2 -r" and it workeed fine, I did it for the remaining repos and it also worked fine, when I did it with repo 1 I got the same error.
am I missing something here? please advice, thanks.
I'm working with MySQL db, and the server and clients are hosted locally, I have SELinux and firewalll both disabled.

and here's the body of the message that I'm getting:

```
patchman -r
Refreshing metadata for all Repos

Repository 1 : Rocky Linux 9 - AppStream x86_64
Downloading repo info:             100%|####################################################################################################|Time:  0:00:00
Found mirrorlist - https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-9
5 mirrors already exist, not adding http://ftp.udx.icscoe.jp/Linux/rocky/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://ftp.ubuntu-tw.net/mirror/rockylinux/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://mirror.nju.edu.cn/rocky/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://mirror.kku.ac.th/rocky-linux/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://mirror.ossplanet.net/mirror/rockylinux/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://mirror.nishi.network/rocky/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://mirrors.isu.net.sa/rocky-mirror/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://repo.jing.rocks/rocky/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://mirrors.ipserverone.com/rocky/9.3/AppStream/x86_64/os/
5 mirrors already exist, not adding http://mirror.ps.kz/rocky/9.3/AppStream/x86_64/os/
Error (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))) - https://rocky-linux-asia-south2.production.gcp.mirrors.ctrliq.cloud/pub/rocky//9.3/AppStream/x86_64/os
Error (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))) - https://rocky-linux-asia-east2.production.gcp.mirrors.ctrliq.cloud/pub/rocky//9.3/AppStream/x86_64/os
Downloading repo info:             100%|####################################################################################################|Time:  0:00:00
Found yum rpm repo - https://rocky-linux-asia-south2.production.gcp.mirrors.ctrliq.cloud/pub/rocky//9.3/AppStream/x86_64/os/repodata/repomd.xml
Downloading package info:          100%|####################################################################################################|Time:  0:00:02
Downloading module info:           100%|####################################################################################################|Time:  0:00:00
Extracting packages:               100%|####################################################################################################|Time:  0:00:00
Fetching existing packages:        100%|####################################################################################################|Time:  0:00:00
(1062, "Duplicate entry 'nodejs' for key 'name'")
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
modules.models.Module.DoesNotExist: Module matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'nodejs' for key 'name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/repos/utils.py", line 329, in extract_module_metadata
    module, c = all_modules.get_or_create(name=m_name,
  File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
django.db.utils.IntegrityError: (1062, "Duplicate entry 'nodejs' for key 'name'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/patchman", line 705, in <module>
    main()
  File "/usr/bin/patchman", line 699, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 665, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/bin/patchman", line 122, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python3.9/site-packages/repos/models.py", line 86, in refresh
    refresh_rpm_repo(self)
  File "/usr/lib/python3.9/site-packages/repos/utils.py", line 716, in refresh_rpm_repo
    refresh_yum_repo(mirror, data, mirror_url, ts)
  File "/usr/lib/python3.9/site-packages/repos/utils.py", line 586, in refresh_yum_repo
    extract_module_metadata(module_data, modules_url, mirror.repo)
  File "/usr/lib/python3.9/site-packages/repos/utils.py", line 337, in extract_module_metadata
    module = all_modules.get(name=m_name,
  File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
modules.models.Module.DoesNotExist: Module matching query does not exist.
```

**Comment by furlongm** [comment]
Do you have any modules enabled on the hosts?

**Comment by Ezio1001** [comment]
> Do you have any modules enabled on the hosts?

Thanks for the fix.
Actually I didn't have any enabled modules, I tried running the command after your latest update it got over the module issue just fine.
However, now is running into another issue this time and here it is:
```
Repository 5 : Rocky Linux 9 - Extras x86_64
Downloading repo info:             100%|#########################################################################################################################################################|Time:  0:00:00
Found mirrorlist - https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=extras-9
5 mirrors already exist, not adding http://repo.jing.rocks/rocky/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://mirror.kku.ac.th/rocky-linux/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://ftp.ubuntu-tw.net/mirror/rockylinux/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://ftp.udx.icscoe.jp/Linux/rocky/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://mirror.nishi.network/rocky/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://mirror.nju.edu.cn/rocky/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://mirror.ossplanet.net/mirror/rockylinux/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://mirror.ps.kz/rocky/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://mirrors.ipserverone.com/rocky/9.3/extras/x86_64/os/
5 mirrors already exist, not adding http://mirrors.isu.net.sa/rocky-mirror/9.3/extras/x86_64/os/
Error (HTTPConnectionPool(host='mirror.kku.ac.th', port=80): Max retries exceeded with url: /rocky-linux/9.3/extras/x86_64/os/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f206a463280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))) - http://mirror.kku.ac.th/rocky-linux/9.3/extras/x86_64/os/
Downloading repo info:             100%|#########################################################################################################################################################|Time:  0:00:02
Found yum rpm repo - https://mirror.nevacloud.com/
Traceback (most recent call last):
  File "/usr/bin/patchman", line 705, in <module>
    main()
  File "/usr/bin/patchman", line 699, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 665, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/bin/patchman", line 122, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python3.9/site-packages/repos/models.py", line 86, in refresh
    refresh_rpm_repo(self)
  File "/usr/lib/python3.9/site-packages/repos/utils.py", line 716, in refresh_rpm_repo
    refresh_yum_repo(mirror, data, mirror_url, ts)
  File "/usr/lib/python3.9/site-packages/repos/utils.py", line 532, in refresh_yum_repo
    primary_url, primary_checksum, primary_checksum_type = get_primary_url(mirror_url, data)
  File "/usr/lib/python3.9/site-packages/repos/utils.py", line 141, in get_primary_url
    location = context.xpath("//ns:data[@type='primary']/ns:location/@href",
IndexError: list index out of range
```
Also, is there a way to minimize the time it takes the server trying to connect to a mirror until it reports a connection error, because it takes a significant amount of time for each failed mirror to report back and error, here is an example of the error so it would better clarify my inquiry: 
```
(Error (HTTPConnectionPool(host='mirror.kku.ac.th', port=80): Max retries exceeded with url: /rocky-linux/9.3/extras/x86_64/os/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faa763d5fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))) - http://mirror.kku.ac.th/rocky-linux/9.3/extras/x86_64/os/)
```
