### ISSUE TITLE
issues from Oracle linux client to Ubuntu 22.04 Server - IndexError: list index out of range

### ISSUE THREAD

**Issue by u-capg** [furlongm/patchman#563]
Moorning
When i try to launch the script on client:
     patchman-client -v 
Server side i have this error:

DEV [root@server-side ]$ [2024-03-06 02:46:10,560: INFO/MainProcess] Task reports.tasks.process_report[0ea1c718-6e66-4f01-a518-3277fcaedacc] received

[2024-03-06 02:46:10,655: ERROR/ForkPoolWorker-4] Task reports.tasks.process_report[0ea1c718-6e66-4f01-a518-3277fcaedacc] raised unexpected: IndexError('list index out of range')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/reports/tasks.py", line 29, in process_report
    report.process(verbose=True)
  File "/usr/lib/python3/dist-packages/reports/models.py", line 171, in process
    process_modules(report=self, host=host)
  File "/usr/lib/python3/dist-packages/reports/utils.py", line 80, in process_modules
    module = process_module(module_str)
  File "/usr/lib/python3/dist-packages/reports/utils.py", line 322, in process_module
    m_version = module_str[2]
**IndexError: list index out of range**

I have server side Ubuntu 22.04 and the client side is Oracle linux 8.9 

Patchman and patchman client are 3.0.8 on both server

Please could you help me

**Comment by u-capg** [comment]
other error i have when i lauch 
patchman-client -s http://172.31.*.*/patchman/

sed: -e expression #1, char 15: unterminated `s' command

Then the command end normally

**Comment by cracksmokinmonkeys** [comment]
Seeing something similar using mysql backend:

Processing Reports for all Hosts
Reverse DNS check disabled
Traceback (most recent call last):   0%|                                                                     |ETA:  --:--:--
  File "/opt/patchman/bin/patchman", line 705, in <module>
    main()
  File "/opt/patchman/bin/patchman", line 699, in main
    showhelp = process_args(args)
  File "/opt/patchman/bin/patchman", line 659, in process_args
    process_reports(args.host, args.force)
  File "/opt/patchman/bin/patchman", line 490, in process_reports
    report.process(find_updates=False)
  File "/opt/patchman/lib64/python3.9/site-packages/reports/models.py", line 169, in process
    process_modules(report=self, host=host)
  File "/opt/patchman/lib64/python3.9/site-packages/reports/utils.py", line 80, in process_modules
    module = process_module(module_str)
  File "/opt/patchman/lib64/python3.9/site-packages/reports/utils.py", line 322, in process_module
    m_version = module_str[2]
IndexError: list index out of range

**Comment by u-capg** [comment]
I have postgresql installed
My configuration is postgresql 15 
Patchman server is Ubuntu 22.04 with pitchman 3.0.8

I have problem with Oracle linux and also Red hat 8

If you could help me to solve

Giovanni

**Comment by cracksmokinmonkeys** [comment]
I was able to get this to work by using the older 3.7 version of patchman-client.

**Comment by u-capg** [comment]
Ok I could use the old version if you are able to solve

**Comment by TW1920** [comment]
I have the same problem on Debian 12.5 (Patchman Core) - but only after added an additional host based on AlmaLinux (Client) - as far as I saw the report is much bigger than of our other servers (Clients). Maybe there's the reason, would explain the error message.

**Comment by furlongm** [comment]
Can you try commit 0404e57c8fc61ce33a88c3ccd7b672a08cdf1083  in PR #594 ? This should fix it but I want to confirm first.

**Comment by fuadsaeed** [comment]
Hello,
Not sure this the right channel apologies if not.
Is there way to the patchman server send patching report by email on
security updates only please?

Kind regards,
Fuad
