### ISSUE TITLE
patchman-client gives error on Oracle Linux 8 with modules

### ISSUE THREAD

**Issue by wellhardh** [furlongm/patchman#580]
I get the following error when running patchman-client (3.0.8-1) on Oracle Linux 8:

```
Checking for modularity...
Finding enabled yum modules...
sed: -e expression #1, char 15: unterminated `s' command
```

```
# yum module list --enabled
Last metadata expiration check: 2:29:18 ago on Wed 08 May 2024 09:27:19 AM CEST.
Oracle Linux 8 Application Stream (x86_64)
Name               Stream     Profiles Summary                                                                                                                                          
container-tools    ol8 [d][e] common [ Most recent (rolling) versions of podman, buildah, skopeo, runc, conmon, runc, conmon, CRIU, Udica, etc as well as dependencies such as container
                              d]       -selinux built and tested together, and updated as frequently as every 12 weeks.
python36           3.6 [d][e] build, c Python programming language, version 3.6                                                                                                         
                              ommon [d 
                              ]        
satellite-5-client 1.0 [d][e] common [ ULN client packages                                                                                                                              
                              d], gui  

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
```

It looks like the error happens in the `get_enabled_modules()` function. I have attached the output from `yum module info python36` that looks to be the problem.

[module_info_python36.txt](https://github.com/furlongm/patchman/files/15247441/module_info_python36.txt)

The output contains information for several versions of the module and my guess is that the code does not handle that. It is however possible to list info for a particular version using:

```
# yum module info python36:3.6:8000020190410133122:17efdbc7:x86_64
Last metadata expiration check: 2:46:08 ago on Wed 08 May 2024 09:27:19 AM CEST.
Name             : python36
Stream           : 3.6 [d][e][a]
Version          : 8000020190410133122
Context          : 17efdbc7
Architecture     : x86_64
Profiles         : build, common [d]
Default profiles : common
Repo             : ol8_appstream
Summary          : Python programming language, version 3.6
Description      : This module gives users access to the internal Python 3.6 in OL8, as
                 : well as provides some additional Python packages the users might need.
                 : In addition to these you can install any python3-* package available
                 : in OL and use it with Python from this module.
Requires         : platform:[el8]
Artifacts        : python-nose-docs-0:1.3.7-30.module+el8.0.0+5333+22a49f57.noarch
                 : python-pymongo-doc-0:3.6.1-9.module+el8.0.0+5333+22a49f57.noarch
                 : python-sqlalchemy-doc-0:1.3.2-1.module+el8.0.0+5333+22a49f57.noarch
                 : python-virtualenv-doc-0:15.1.0-18.module+el8.0.0+5333+22a49f57.noarch
                 : python3-PyMySQL-0:0.8.0-10.module+el8.0.0+5333+22a49f57.noarch
                 : python3-bson-0:3.6.1-9.module+el8.0.0+5333+22a49f57.x86_64
                 : python3-docs-0:3.6.7-2.module+el8.0.0+5333+22a49f57.noarch
                 : python3-docutils-0:0.14-12.module+el8.0.0+5333+22a49f57.noarch
                 : python3-nose-0:1.3.7-30.module+el8.0.0+5333+22a49f57.noarch
                 : python3-pygments-0:2.2.0-20.module+el8.0.0+5333+22a49f57.noarch
                 : python3-pymongo-0:3.6.1-9.module+el8.0.0+5333+22a49f57.x86_64
                 : python3-pymongo-gridfs-0:3.6.1-9.module+el8.0.0+5333+22a49f57.x86_64
                 : python3-scipy-0:1.0.0-19.module+el8.0.0+5333+22a49f57.x86_64
                 : python3-sqlalchemy-0:1.3.2-1.module+el8.0.0+5333+22a49f57.x86_64
                 : python3-virtualenv-0:15.1.0-18.module+el8.0.0+5333+22a49f57.noarch
                 : python3-wheel-1:0.30.0-15.module+el8.0.0+5333+22a49f57.noarch
                 : python36-0:3.6.8-2.module+el8.0.0+5333+22a49f57.x86_64
                 : python36-debug-0:3.6.8-2.module+el8.0.0+5333+22a49f57.x86_64
                 : python36-devel-0:3.6.8-2.module+el8.0.0+5333+22a49f57.x86_64
                 : python36-rpm-macros-0:3.6.8-2.module+el8.0.0+5333+22a49f57.noarch

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled, [a]ctive
```

**Comment by furlongm** [comment]
Can you try commit 0404e57c8fc61ce33a88c3ccd7b672a08cdf1083  in PR #594 ? This should fix it but I want to confirm first.

**Comment by wellhardh** [comment]
Thanks for your help. I tried your fix and it works a bit better. The "sed" error is gone but the patchman-client produces module output that the report processor trips on.

Module output attached. Note the string "Artifacts: " that looks suspect. 

[modules-output.txt](https://github.com/user-attachments/files/16458442/modules-output.txt)

Report processing:
`# /usr/bin/patchman -u -p -H host.example.com
Processing Reports for Host host.example.com
Reverse DNS check disabled
host.example.com repos           100%|############################################|Time:  0:00:00
host.example.com modules         N/A%|                                            |ETA:  --:--:--Error parsing package string: "Artifacts"
Traceback (most recent call last):
  File "/usr/bin/patchman", line 705, in <module>
    main()
  File "/usr/bin/patchman", line 699, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 659, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 490, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python3.9/site-packages/reports/models.py", line 171, in process
    process_modules(report=self, host=host)
  File "/usr/lib/python3.9/site-packages/reports/utils.py", line 80, in process_modules
    module = process_module(module_str)
  File "/usr/lib/python3.9/site-packages/reports/utils.py", line 339, in process_module
    p_name, p_epoch, p_ver, p_rel, p_dist, p_arch = parse_package_string(pkg_str)
TypeError: cannot unpack non-iterable NoneType object
`

Please let me know if you need output from a command etc so you can see what input patchmaker-client gets from the host.

**Comment by furlongm** [comment]
@wellhardh can you give the output of the following commands?

```
yum module list --enabled
```

and

```
yum module info XXX
```

for all enabled modules?

**Comment by wellhardh** [comment]
```
[ ~]# yum module list --enabled
Last metadata expiration check: 0:14:00 ago on Tue 06 Aug 2024 11:19:41 AM CEST.
Oracle Linux 8 Application Stream (x86_64)
Name                 Stream         Profiles              Summary
container-tools      ol8 [d][e]     common [d]            Most recent (rolling) versions of podman, buildah, skopeo, runc, conmon, runc, conmon, CRIU, Udica, etc as well as dependencies such as container-selinux built and tested together, and updated as frequently as every 12 weeks.
perl                 5.26 [d][e]    common [d], minimal   Practical Extraction and Report Language
perl-IO-Socket-SSL   2.066 [d][e]   common [d]            Perl library for transparent TLS
perl-libwww-perl     6.34 [d][e]    common [d]            A Perl interface to the World-Wide Web
python36             3.6 [d][e]     build, common [d]     Python programming language, version 3.6
satellite-5-client   1.0 [d][e]     common [d], gui       ULN client packages

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
[ ~]# yum module info container-tools > /tmp/container-tools.txt
[ ~]# yum module info perl > /tmp/perl.txt
[ ~]# yum module info perl-IO-Socket-SSL > /tmp/perl-IO-Socket-SSL.txt
[ ~]# yum module info perl-libwww-perl > /tmp/perl-libwww-perl.txt
[ ~]# yum module info python36 > /tmp/python36.txt
[ ~]# yum module info satellite-5-client > /tmp/satellite-5-client.txt
```

Output from `yum module info` in attached file. 
[module-info.tgz](https://github.com/user-attachments/files/16508519/module-info.tgz)

**Comment by furlongm** [comment]
@wellhardh can you check to see if #605 fixes the issue for you?

**Comment by wellhardh** [comment]
It works! Thanks for your help.
