### ISSUE TITLE
InvalidTemplateLibrary at /login/ after installing on CentOS 7

### ISSUE THREAD

**Issue by RicardoJeronimo** [furlongm/patchman#67]
Hey!

I'm trying to install this on a CentOS 7 machine since the INSTALL.md was updated and I've ran into some issues. This is what I did:

-  Downloaded all the RPMs from http://repo.openbytes.ie/yum, since the repo is missing python-django-extensions, and got the missing package from [here](https://www.rpmfind.net/linux/rpm2html/search.php?query=python2-django-extensions&submit=Search+...);

- Did `yum install httpd mod_wsgi` and `yum localinstall *.rpm`;

- Finally did `patchman-manage createsuperuser` and then `patchman-manage migrate --run-syncdb`.

After enabling `DEBUG = True`, I get the following error:
![image](https://user-images.githubusercontent.com/4950815/49439157-392b9200-f7b8-11e8-8874-88546c709e47.png)

What am I missing here?

**Comment by furlongm** [comment]
Hmm, I must have missed adding that rpm. Can you try with this one?

https://download.opensuse.org/repositories/home:/furlongm:/python/Fedora_28/noarch/python-django-extensions-2.0.8-3.1.noarch.rpm

**Comment by furlongm** [comment]
For the above error, try installing python-humanize. Looks like a missing dependency.

**Comment by RicardoJeronimo** [comment]
Python-humanize did the trick, thanks! I also tested that RPM you linked and the server is running as expected.

There is a problem, however, with `patchman -a`. I get this output when I send a report from the server to itself with `patchman-client -s http://127.0.0.1/patchman`:
```
[root@centossrv02 ~]# patchman -a
Cleaning Reports for all Hosts

Processing Reports for all Hosts
Reverse DNS mismatch found: centossrv02.mainroad.mgt != localhost
Traceback (most recent call last):  33%|################################################                                                                                                |ETA:  0:00:00
  File "/usr/bin/patchman", line 593, in <module>
    main()
  File "/usr/bin/patchman", line 588, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 555, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 430, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python2.7/site-packages/patchman/reports/models.py", line 151, in process
    process_repos(report=self, host=host)
  File "/usr/lib/python2.7/site-packages/patchman/reports/utils.py", line 43, in process_repos
    repo, priority = process_repo(repo_str, report.arch)
  File "/usr/lib/python2.7/site-packages/patchman/reports/utils.py", line 213, in process_repo
    if repo[2] == '':
IndexError: list index out of range
```

I disabled "Check dns" but nothing changed. Is this due to some missing dependency or something like that?

**Comment by furlongm** [comment]
This is fixed in the client on master, deleting reports and downloading the client from master should fix it. I'll do a release with the fix shortly. See #65 for details.
