### ISSUE TITLE
Unknown checksum type: sha1

### ISSUE THREAD

**Issue by alexjfisher** [furlongm/patchman#75]
Trying out patchman for the first time.  Seems upset about one of my repos though. (https://packagecloud.io/prometheus-rpm/release/el/7/x86_64 mirrored by pulp)

```
Unknown checksum type: sha1
Traceback (most recent call last):
  File "/bin/patchman", line 593, in <module>
    main()
  File "/bin/patchman", line 588, in main
    showhelp = process_args(args)
  File "/bin/patchman", line 561, in process_args
    refresh_repos(args.repo, args.force)
  File "/bin/patchman", line 120, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python2.7/site-packages/patchman/repos/models.py", line 88, in refresh
    refresh_rpm_repo(self)
  File "/usr/lib/python2.7/site-packages/patchman/repos/utils.py", line 552, in refresh_rpm_repo
    refresh_yum_repo(mirror, data, mirror_url, ts)
  File "/usr/lib/python2.7/site-packages/patchman/repos/utils.py", line 435, in refresh_yum_repo
    sha = get_sha(checksum_type, data)
  File "/usr/lib/python2.7/site-packages/patchman/repos/utils.py", line 174, in get_sha
    return sha
UnboundLocalError: local variable 'sha' referenced before assignment
```

Maybe `sha` and `sha1` are synonyms and a simple change [here](https://github.com/furlongm/patchman/blob/b7678fdf62fc974d87c382f7d43d82ccb264a032/patchman/repos/utils.py#L167) would work???

**Comment by alexjfisher** [comment]
From https://www.systutorials.com/docs/linux/man/8-createrepo/ ...
> -s --checksum
Choose the checksum type used in repomd.xml and for packages in the metadata. The default is now "sha256" (if python has hashlib). The older default was "sha", which is actually "sha1", however explicitly using "sha1" doesn't work on older (3.0.x) versions of yum, you need to specify "sha".
